import type { Attempt, MotionSignatureStyle, Project } from '../types/klym';

export const defaultStyle: MotionSignatureStyle = 'data';

export const seedProjects: Project[] = [
  {
    id: 'project_concrete_traverse',
    displayName: 'CONCRETE TRAVERSE',
    localName: '콘크리트 트래버스',
    gymName: 'THE CLIMB · SEONGSU',
    wallName: 'WALL 03',
    grade: 'V6',
    problemName: 'Concrete Traverse',
    notes: 'Long rightward line on dark volumes. Sharp finish after the deadpoint.',
    betaNotes: 'Right heel hook on volume, deadpoint to crimp, match feet before throw.',
    nextAttemptStrategy: 'Commit to the heel, then move faster through the top crimp.',
    status: 'projecting',
    attemptsCount: 14,
    createdAt: '2026-04-19T09:30:00.000Z',
    updatedAt: '2026-04-27T12:22:00.000Z',
    seed: 7,
  },
  {
    id: 'project_crimson_dyno',
    displayName: 'CRIMSON DYNO',
    localName: '크림슨 다이노',
    gymName: 'BURN · HONGDAE',
    wallName: 'WALL 07',
    grade: 'V7',
    problemName: 'Crimson Dyno',
    notes: 'Compression start with a clean throw to the upper jug.',
    betaNotes: 'Big throw from undercling. Set hips, full extension, latch jug top-out.',
    nextAttemptStrategy: 'Push through the right foot instead of pulling early.',
    status: 'close',
    attemptsCount: 22,
    createdAt: '2026-04-15T10:00:00.000Z',
    updatedAt: '2026-04-28T05:05:00.000Z',
    seed: 13,
  },
  {
    id: 'project_graphite_slab',
    displayName: 'GRAPHITE SLAB',
    localName: '그라파이트 슬랩',
    gymName: 'THE CLIMB · SEONGSU',
    wallName: 'SLAB 01',
    grade: 'V5',
    problemName: 'Graphite Slab',
    notes: 'Low-volume slab. Foot trust more than power.',
    betaNotes: 'Trust the feet. Left smear, slow shift, no hands needed for the bump.',
    nextAttemptStrategy: 'Breathe before the stand-up and keep hips over the left foot.',
    status: 'projecting',
    attemptsCount: 6,
    createdAt: '2026-04-24T07:00:00.000Z',
    updatedAt: '2026-04-24T09:10:00.000Z',
    seed: 21,
  },
  {
    id: 'project_paper_tiger',
    displayName: 'PAPER TIGER',
    localName: '페이퍼 타이거',
    gymName: 'PEAKERS · GANGNAM',
    wallName: 'COMP',
    grade: 'V8',
    problemName: 'Paper Tiger',
    notes: 'Compression boulder with a moving toe-hook.',
    betaNotes: 'Compression start, hold the swing on toe-hook, dyno to sloper.',
    nextAttemptStrategy: 'Reset the toe before the throw; avoid cutting feet too soon.',
    status: 'projecting',
    attemptsCount: 31,
    createdAt: '2026-04-04T09:00:00.000Z',
    updatedAt: '2026-04-22T11:30:00.000Z',
    seed: 33,
  },
  {
    id: 'project_night_shift',
    displayName: 'NIGHT SHIFT',
    localName: '나이트 시프트',
    gymName: 'V1 · ITAEWON',
    wallName: 'CAVE',
    grade: 'V6',
    problemName: 'Night Shift',
    notes: 'Sent after finding a quieter foot sequence.',
    betaNotes: 'Keep left knee dropped through the roof. Bump right hand only after feet settle.',
    nextAttemptStrategy: '',
    status: 'sent',
    attemptsCount: 9,
    createdAt: '2026-04-14T09:00:00.000Z',
    updatedAt: '2026-04-21T12:00:00.000Z',
    sentAt: '2026-04-21T12:00:00.000Z',
    seed: 41,
  },
  {
    id: 'project_street_line',
    displayName: 'STREET LINE',
    localName: '스트리트 라인',
    gymName: 'THE CLIMB · SEONGSU',
    wallName: 'WALL 02',
    grade: 'V4',
    problemName: 'Street Line',
    notes: 'Quick send. Good first card material.',
    betaNotes: 'Stay square, catch the left sidepull with a high foot.',
    nextAttemptStrategy: '',
    status: 'sent',
    attemptsCount: 4,
    createdAt: '2026-04-16T09:00:00.000Z',
    updatedAt: '2026-04-18T12:00:00.000Z',
    sentAt: '2026-04-18T12:00:00.000Z',
    seed: 53,
  },
];

export const seedAttempts: Attempt[] = [
  {
    id: 'attempt_001',
    projectId: 'project_concrete_traverse',
    date: '2026-04-27',
    attemptCount: 3,
    result: 'close',
    notes: 'Fell matching the top crimp. Heel beta is working.',
  },
  {
    id: 'attempt_002',
    projectId: 'project_concrete_traverse',
    date: '2026-04-25',
    attemptCount: 4,
    result: 'beta',
    notes: 'Changed to a right heel hook. More stable through the middle.',
  },
  {
    id: 'attempt_003',
    projectId: 'project_crimson_dyno',
    date: '2026-04-28',
    attemptCount: 5,
    result: 'close',
    notes: 'Caught the jug twice but cut too hard on the swing.',
  },
  {
    id: 'attempt_004',
    projectId: 'project_night_shift',
    date: '2026-04-21',
    attemptCount: 2,
    result: 'send',
    notes: 'Clean send. Best attempt of the session.',
  },
  {
    id: 'attempt_005',
    projectId: 'project_street_line',
    date: '2026-04-18',
    attemptCount: 1,
    result: 'send',
    notes: 'Second-day send.',
  },
];

export const gyms = ['THE CLIMB · SEONGSU', 'BURN · HONGDAE', 'PEAKERS · GANGNAM', 'V1 · ITAEWON'];
